/* 
   Portfolio Interactions - تالين أشقر 
   Author: Taleen Ashqar (Generated by Antigravity)
   Date: 2026
*/

document.addEventListener('DOMContentLoaded', () => {
    // 1. Dynamic Year Update
    const yearSpan = document.getElementById('year');
    if (yearSpan) {
        yearSpan.textContent = new Date().getFullYear();
    }

    // 2. Scroll Reveal Animation
    const revealElements = document.querySelectorAll('.reveal');

    const revealOnScroll = () => {
        for (let i = 0; i < revealElements.length; i++) {
            const windowHeight = window.innerHeight;
            const elementTop = revealElements[i].getBoundingClientRect().top;
            const elementVisible = 150;

            if (elementTop < windowHeight - elementVisible) {
                revealElements[i].classList.add('reveal-active');
            } else {
                // Optional: remove class to animate again when scrolling up
                // revealElements[i].classList.remove('reveal-active');
            }
        }
    };

    // Run once on load
    revealOnScroll();

    // Run on scroll
    window.addEventListener('scroll', revealOnScroll);

    // 3. Simple Button Hover Log (Can be expanded for analytics/feedback)
    const socialBtns = document.querySelectorAll('.social-btn');
    socialBtns.forEach(btn => {
        btn.addEventListener('mouseenter', () => {
            console.log(`Hovering over: ${btn.textContent.trim()}`);
            // Add any additional micro-interaction here
        });
    });
});
